import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../../../core/constants/app_colors.dart';
import '../../../services/firebase_service.dart';
import '../../../services/cache/smart_data_repository.dart';
import 'package:provider/provider.dart';

/// Doctor/Therapist Report — generates a professional, shareable
/// summary of the child's profile, skills, activities, and milestones.
class DoctorReportScreen extends StatefulWidget {
  const DoctorReportScreen({super.key});

  @override
  State<DoctorReportScreen> createState() => _DoctorReportScreenState();
}

class _DoctorReportScreenState extends State<DoctorReportScreen> {
  final _firebaseService = FirebaseService();
  bool _isLoading = true;
  String _report = '';
  String? _childName;

  @override
  void initState() {
    super.initState();
    _generateReport();
  }

  Future<void> _generateReport() async {
    try {
      final repository = context.read<SmartDataRepository>();
      final uid = _firebaseService.currentUser?.uid;
      if (uid == null) throw Exception("User not logged in");

      final childProfile = await _firebaseService.getChildProfile();
      final userProfile = await repository.getUserProfile(uid);
      final dashboard = await repository.getDashboardData(uid);
      
      final skillProgress = Map<String, double>.from(dashboard['skillProgress'] ?? {});
      final weeklyStats = dashboard['weeklyStats'] ?? {'count': 0, 'minutes': 0, 'streak': 0};
      final activityLogs = await _firebaseService.getActivityLogs(limit: 5);
      final milestones = await _firebaseService.getMilestones();

      final buf = StringBuffer();

      buf.writeln('═══════════════════════════════════════');
      buf.writeln('       CARE-AI PROGRESS REPORT');
      buf.writeln('       For Healthcare Provider');
      buf.writeln('═══════════════════════════════════════');
      buf.writeln();
      buf.writeln(
        'Report Date: ${DateTime.now().toIso8601String().substring(0, 10)}',
      );
      buf.writeln('Generated by: CARE-AI v1.0.0');
      buf.writeln('Parent/Caregiver: ${userProfile?.displayName ?? 'N/A'}');
      buf.writeln();

      if (childProfile != null) {
        _childName = childProfile.name;

        buf.writeln('━━━ CHILD PROFILE ━━━━━━━━━━━━━━━━━━━');
        buf.writeln('Name: ${childProfile.name}');
        buf.writeln('Age: ${childProfile.age} years');
        if (childProfile.gender != null) {
          buf.writeln('Gender: ${childProfile.gender}');
        }
        buf.writeln('Conditions: ${childProfile.conditions.join(', ')}');
        buf.writeln('Communication Level: ${childProfile.communicationLevel}');
        buf.writeln('Motor Skill Level: ${childProfile.motorSkillLevel}');
        buf.writeln('Current Therapy: ${childProfile.currentTherapyStatus}');
        buf.writeln();

        if (childProfile.behavioralConcerns.isNotEmpty) {
          buf.writeln('Behavioral Concerns:');
          for (final c in childProfile.behavioralConcerns) {
            buf.writeln('  • $c');
          }
          buf.writeln();
        }

        if (childProfile.sensoryIssues.isNotEmpty) {
          buf.writeln('Sensory Sensitivities:');
          for (final s in childProfile.sensoryIssues) {
            buf.writeln('  • $s');
          }
          buf.writeln();
        }

        if (childProfile.parentGoals.isNotEmpty) {
          buf.writeln('Parent Goals:');
          for (final g in childProfile.parentGoals) {
            buf.writeln('  • $g');
          }
          buf.writeln();
        }
      } else {
        buf.writeln('⚠️ No child profile has been set up yet.');
        buf.writeln();
      }

      // Real skill progress from activity logs
      buf.writeln('━━━ SKILL PROGRESS ━━━━━━━━━━━━━━━━━━');
      if (skillProgress.isEmpty) {
        buf.writeln('No skill data available yet.');
      } else {
        for (final entry in skillProgress.entries) {
          final pct = (entry.value * 100).toInt();
          final filled = (pct / 5).round();
          final empty = 20 - filled;
          buf.writeln(
            '${entry.key.padRight(16)} ${'█' * filled}${'░' * empty}  $pct%',
          );
        }
      }
      buf.writeln();

      // Real weekly summary
      buf.writeln('━━━ WEEKLY SUMMARY ━━━━━━━━━━━━━━━━━━');
      buf.writeln('Activities Completed: ${weeklyStats['count']}');
      buf.writeln('Total Minutes: ${weeklyStats['minutes']}');
      buf.writeln('Current Streak: ${weeklyStats['streak']} days');
      buf.writeln();

      // Real recent activities
      buf.writeln('━━━ RECENT ACTIVITIES ━━━━━━━━━━━━━━━');
      if (activityLogs.isEmpty) {
        buf.writeln('No activities logged yet.');
      } else {
        for (final log in activityLogs) {
          final mins = (log.durationSeconds / 60).round();
          final ago = _timeAgo(log.completedAt);
          buf.writeln('✓ ${log.activityTitle} ($mins min) — $ago');
        }
      }
      buf.writeln();

      // Real milestones
      buf.writeln('━━━ MILESTONES ACHIEVED ━━━━━━━━━━━━━');
      if (milestones.isEmpty) {
        buf.writeln('No milestones recorded yet.');
      } else {
        for (final m in milestones) {
          buf.writeln(
            '${m['emoji'] ?? '⭐'} ${m['title'] ?? 'Milestone'} — ${m['category'] ?? ''}',
          );
        }
      }
      buf.writeln();

      buf.writeln('═══════════════════════════════════════');
      buf.writeln('⚠️ DISCLAIMER: This report is generated by');
      buf.writeln('CARE-AI, an AI-powered parenting companion.');
      buf.writeln('It does NOT constitute a medical diagnosis.');
      buf.writeln('Please use this as a supplementary reference');
      buf.writeln('for your healthcare discussions.');
      buf.writeln('═══════════════════════════════════════');

      if (mounted) {
        setState(() {
          _report = buf.toString();
          _isLoading = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() {
          _report = 'Error generating report: $e';
          _isLoading = false;
        });
      }
    }
  }

  String _timeAgo(DateTime date) {
    final diff = DateTime.now().difference(date);
    if (diff.inMinutes < 60) return '${diff.inMinutes}m ago';
    if (diff.inHours < 24) return '${diff.inHours}h ago';
    if (diff.inDays == 1) return 'Yesterday';
    if (diff.inDays < 7) return '${diff.inDays}d ago';
    return '${date.day}/${date.month}';
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      appBar: AppBar(
        title: const Text('Doctor Report'),
        actions: [
          if (!_isLoading)
            IconButton(
              onPressed: () {
                Clipboard.setData(ClipboardData(text: _report));
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(
                    content: Text('Report copied to clipboard! 📋'),
                    backgroundColor: AppColors.success,
                  ),
                );
              },
              icon: const Icon(Icons.copy_rounded, size: 22),
              tooltip: 'Copy Report',
            ),
        ],
      ),
      body:
          _isLoading
              ? const Center(child: CircularProgressIndicator())
              : SingleChildScrollView(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Header card
                    Container(
                      width: double.infinity,
                      padding: const EdgeInsets.all(20),
                      decoration: BoxDecoration(
                        gradient: const LinearGradient(
                          colors: [Color(0xFF0EA5E9), Color(0xFF38BDF8)],
                          begin: Alignment.topLeft,
                          end: Alignment.bottomRight,
                        ),
                        borderRadius: BorderRadius.circular(20),
                        boxShadow: [
                          BoxShadow(
                            color: const Color(
                              0xFF0EA5E9,
                            ).withValues(alpha: 0.3),
                            blurRadius: 20,
                            offset: const Offset(0, 8),
                          ),
                        ],
                      ),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Row(
                            children: [
                              Icon(
                                Icons.medical_information_rounded,
                                color: Colors.white,
                                size: 24,
                              ),
                              SizedBox(width: 10),
                              Text(
                                'Healthcare Provider Report',
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 18,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                            ],
                          ),
                          const SizedBox(height: 8),
                          Text(
                            _childName != null
                                ? 'Generated for ${_childName!}'
                                : 'Generated from CARE-AI data',
                            style: TextStyle(
                              color: Colors.white.withValues(alpha: 0.9),
                              fontSize: 13,
                            ),
                          ),
                        ],
                      ),
                    ).animate().fadeIn(duration: 500.ms),

                    const SizedBox(height: 20),

                    // Report content
                    Container(
                      width: double.infinity,
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        color:
                            isDark
                                ? AppColors.darkCardBackground
                                : AppColors.cardBackground,
                        borderRadius: BorderRadius.circular(16),
                        border:
                            isDark
                                ? Border.all(
                                  color: AppColors.darkBorder.withValues(
                                    alpha: 0.3,
                                  ),
                                )
                                : null,
                      ),
                      child: SelectableText(
                        _report,
                        style: TextStyle(
                          fontFamily: 'monospace',
                          fontSize: 12,
                          height: 1.5,
                          color:
                              isDark
                                  ? AppColors.darkTextPrimary
                                  : AppColors.textPrimary,
                        ),
                      ),
                    ).animate().fadeIn(delay: 200.ms, duration: 500.ms),

                    const SizedBox(height: 20),

                    // Copy button
                    SizedBox(
                      width: double.infinity,
                      child: ElevatedButton.icon(
                        onPressed: () {
                          Clipboard.setData(ClipboardData(text: _report));
                          ScaffoldMessenger.of(context).showSnackBar(
                            const SnackBar(
                              content: Text(
                                'Report copied! Share it with your healthcare provider 📋',
                              ),
                              backgroundColor: AppColors.success,
                            ),
                          );
                        },
                        icon: const Icon(Icons.share_rounded),
                        label: const Text('Copy & Share with Doctor'),
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFF0EA5E9),
                          foregroundColor: Colors.white,
                          padding: const EdgeInsets.symmetric(vertical: 16),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(14),
                          ),
                          elevation: 0,
                        ),
                      ),
                    ).animate().fadeIn(delay: 400.ms, duration: 500.ms),
                  ],
                ),
              ),
    );
  }
}
