/// Predicts the trajectory of the user's mental state over the next 7 days.
enum RiskForecastTrajectory {
  improving,
  stable,
  declining,
}

/// A structured warning level regarding the predicted future state.
enum FutureRiskLevel {
  low,
  medium,
  high,
}

/// Hold the prediction result generated by the AI based on historical data.
class RiskForecastModel {
  final FutureRiskLevel level;
  final RiskForecastTrajectory trajectory;
  final String analysisText;
  final List<String> preventativeTips;
  final DateTime generatedAt;

  const RiskForecastModel({
    required this.level,
    required this.trajectory,
    required this.analysisText,
    required this.preventativeTips,
    required this.generatedAt,
  });

  /// Factory constructor to parse the JSON response from Gemini.
  factory RiskForecastModel.fromJson(Map<String, dynamic> json) {
    FutureRiskLevel parsedLevel = FutureRiskLevel.low;
    final String levelStr = (json['level']?.toString() ?? 'low').toLowerCase();
    if (levelStr == 'medium') parsedLevel = FutureRiskLevel.medium;
    if (levelStr == 'high') parsedLevel = FutureRiskLevel.high;

    RiskForecastTrajectory parsedTrajectory = RiskForecastTrajectory.stable;
    final String trajStr = (json['trajectory']?.toString() ?? 'stable').toLowerCase();
    if (trajStr == 'improving') parsedTrajectory = RiskForecastTrajectory.improving;
    if (trajStr == 'declining') parsedTrajectory = RiskForecastTrajectory.declining;

    return RiskForecastModel(
      level: parsedLevel,
      trajectory: parsedTrajectory,
      analysisText: json['analysis']?.toString() ?? 'Insufficient data to generate a detailed analysis.',
      preventativeTips: (json['preventativeTips'] as List<dynamic>?)
              ?.map((e) => e.toString())
              .toList() ??
          [],
      generatedAt: DateTime.now(),
    );
  }
}
